### ISSUE TITLE
Don't include jars in project

### ISSUE THREAD

**Issue by non** [MoeOrganization/moe#2]
It would be better to include the scalatest jar via a dependency in build.sbt.

For example, something like:

```
name := "moe"

version := "0.0.1"

scalaVersion := "2.9.2"

libraryDependencies += "org.scalatest" %% "scalatest" % "1.9.1" % "test"
```

Hope this helps!

**Comment by gphat** [comment]
Good catch. I've incorporated this suggestion into [pull request 10](https://github.com/stevan/moe/pull/10).

I chose to use scala 2.10.0 since it's out and this project is new enough to not worry about deps catching up.
