### ISSUE TITLE
Namespace squatting

### ISSUE THREAD

**Issue by tobyink** [MoeOrganization/moe#20]
moe.org is already a registered domain name (which does not belong to stevan).

I wish I could recommend registering moe.pl in Poland, but that's taken too.

**Comment by stevan** [comment]
moe-lang is open though

**Comment by genehack** [comment]
moe-perl5.org, to emphasize this is "Mo' Perl5" -- not so much a new thing as a re-envisioning.

**Comment by stevan** [comment]
@genehack++

**Comment by tobyink** [comment]
moe.perl.org? Ask Ask?

**Comment by stevan** [comment]
@tobyink++

**Comment by stevan** [comment]
To be honest, I am not rushing out to get this right now, lets see if we can get the project off the ground first.

**Comment by genehack** [comment]
@stevan++ ;^)
