### ISSUE TITLE
Add editline support to the REPL

### ISSUE THREAD

**Issue by stevan** [MoeOrganization/moe#38]
Currently there is no line editing or history support in the REPL. There are a number of libraries out there, JLine looked to be the simplest and most featureful, however it wasn't so simple to just use it because sbt also uses JLine and so the two collide when used together.

**Comment by jasonmay** [comment]
I wonder if you can exec yourself outside of sbt for the REPL

**Comment by ghost** [comment]
Yeah, using jLine should not itself be much of a problem -  the idea is that we can add repl as one of the tasks or make it(repl) spawn off the main class if no arguments were given.

**Comment by uvtc** [comment]
I don't recall how Clojure handles this, but it might be useful to take a look at its [Leiningen](http://leiningen.org/) project/package management tool (which also takes care of providing a repl) to see how it does it.
