### ISSUE TITLE
Build support for creating a 'moe' executable

### ISSUE THREAD

**Issue by stevan** [MoeOrganization/moe#39]
This gets a little tricky since we have some jars we depend on, but there seem to be a number of solutions out there to bundle things up.

**Comment by uvtc** [comment]
To start off with, it'd be ok with me to have to run my scripts like so:

```
moe my-script.moe
```

**Comment by stevan** [comment]
@uvtc sorry my wording was bad (not enough coffee yet), that is what I would like to do as well, have a 'moe' executable.

**Comment by ghost** [comment]
Executable? Or shell and batch script wrapper like clojure and scala does?

**Comment by stevan** [comment]
@svatsan I suppose that would be sufficient too, I think the primary goal is to be able to do

```
moe my-script.moe
```

**Comment by stevan** [comment]
done, using sbt assembly
