### ISSUE TITLE
Improve handling of ranges in the parser and interpreter

### ISSUE THREAD

**Issue by stevan** [MoeOrganization/moe#50]
The way ranges are handled in the parser is not ideal, currently it only supports Integers and can only parse literals and variables. 

Here is the parser code:

https://github.com/MoeOrganization/moe/blob/master/src/main/scala/org/moe/parser/Expressions.scala#L43

And here is the interpreter code:

https://github.com/MoeOrganization/moe/blob/master/src/main/scala/org/moe/interpreter/Interpreter.scala#L139

**Comment by prakashk** [comment]
https://github.com/MoeOrganization/moe/pull/54 adds support for string ranges.

**Comment by stevan** [comment]
I think this is good enough to close now
