### ISSUE TITLE
More Interpreter tests

### ISSUE THREAD

**Issue by jasonmay** [MoeOrganization/moe#53]
When adding interpreter features I am testing the bare minimum to make sure it works so I can move on to the next interpreter feature. We could use way more tests for edge cases and things like that to ensure robustness.

**Comment by stevan** [comment]
Jason, 

That is fine, we can come up behind and fill in details. Tests are always a nice place to start familiarizing oneself with a project.

Stevan

**Comment by stevan** [comment]
I would prefer to actually do these as language tests, like the ones i have in t/ already
